name: process pull request

on:
  workflow_run:
    workflows: [build pull request]
    types: [completed]

permissions: write-all

jobs:
  process-pr:
    runs-on: ubuntu-latest
    name: Process pull request
    steps:
      - name: Process pull request
        uses: showyourwork/showyourwork-action/process-pull-request@v1
